apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-01-25T19:03:28Z"
  generation: 1
  labels:
    app: bb-clustervolume
  name: bb-clustervolume
  namespace: labproj18
  resourceVersion: "79855261"
  uid: 7c24494c-b6aa-4a76-972d-1f16898874ff
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bb-clustervolume
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bb-clustervolume
    spec:
      containers:
      - command:
        - sleep
        - "9000"
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/default/busybox
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
