apiVersion: v1
kind: ConfigMap
metadata:
  name: currency-app-configmap
  namespace: labproj18
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/curriencies
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-app-deployment
  namespace: labproj18
spec:
  selector:
    matchLabels:
      app: currency-app
  replicas: 1
  template:
    metadata:
      labels:
        app: currency-app
    spec:
      containers:
        - name: currency-app
          image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj18/currencyapp:1.0
          envFrom:
            - configMapRef:
                name: currency-app-configmap
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: labproj18
  name: currency-app-service
spec:
  selector:
    app: currency-app
  ports:
    - port: 8081
      targetPort: 8080
