apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: labproj18
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
